### ISSUE TITLE
Fast string parsing

### ISSUE THREAD

**Issue by paf31** [purescript/roadmap#16]

**Comment by Thimoteus** [comment]
Are there any existing benchmarks to compare against?

Also, I'll just leave this here: https://github.com/paf31/purescript-parser-generator

**Comment by paf31** [comment]
I'd just like something faster than `purescript-parsing`, which can be quite slow. I'd be happy to accept a simpler API to get it. And yes, that's the sort of approach I was experimenting with. It's pretty decent, and I think there is some promise there if someone wants to pick it up.

This seems like a possible "killer app" for PureScript.
