### ISSUE TITLE
Resurrect Online Meetup

### ISSUE THREAD

**Issue by paf31** [purescript/roadmap#33]

**Comment by texastoland** [comment]
Is there any way to help with this? I was thinking of making a Meetup page to coordinate.

**Comment by paf31** [comment]
Definitely. I used to just schedule something informally on Twitter once every couple of weeks, but a Meetup page would be better (although not free). The tricky bit was always finding speakers.

**Comment by texastoland** [comment]
I have a list of over 70 people. I feel confident I could pull it together once or twice a month. @spicydonuts offered to help too. I'll look into cost this week.

**Comment by paf31** [comment]
Another option is to live stream the new Bay Area group meetings, if we can figure out how to do that.

**Comment by texastoland** [comment]
Might be less interactive than a Hangout for online attendees? I was amazed at the participation when Hardy presented Lens.

**Comment by texastoland** [comment]
Okay I researched video conferencing and paying for Zoom.us. May I list it via your [SF Meetup](http://www.meetup.com/Bay-Area-PureScript-Meetup/)? Trying biweekly. For the first one I'm asking contributors to show off their 0.8.1 features.

**Comment by maddie927** [comment]
That sounds great

**Comment by paf31** [comment]
Certainly feel free to put the word out on the meetup, but I don't know if it is the best place to advertise right now, since there are only 53 members. Twitter could have a much better reach.

**Comment by texastoland** [comment]
Advertising exclusively via Twitter but wanting Meetup as hub for scheduling, attendance, outlines, and links to video connection and presentation content. Add me as an organizer or DM?

**Comment by texastoland** [comment]
Ready to close unless you want to wait till the first meeting :shipit:

**Comment by paf31** [comment]
Thanks!
