### ISSUE TITLE
Daily PureScript video

### ISSUE THREAD

**Issue by paf31** [purescript/roadmap#36]

**Comment by texastoland** [comment]
YouTube channel is ready. Zoom is available for recording. Did you envision tips, or community live coding? Any concern about bit rot?

**Comment by paf31** [comment]
Another neat option which I've been trying lately is to use asciinema. Making a daily video that way would be much simpler.

**Comment by paf31** [comment]
I'm going to close this, since we now have regular online meetups which are frequently recorded. I would still like to spend more time making asciinema videos though 😄
