### ISSUE TITLE
purescript-brunch

### ISSUE THREAD

**Issue by texastoland** [purescript/roadmap#46]
PureScript takes a bit of manual work to get started with. Perhaps a [Brunch](http://brunch.io) [plugin](https://github.com/brunch/brunch/blob/master/docs/plugins.md) and [skeleton](https://github.com/brunch/dead-simple) could wrap other recommended tools like [psa](https://github.com/natefaubion/purescript-psa) or [psc-pane](https://github.com/anttih/psc-pane), [Pulp](https://github.com/bodil/pulp), etc. Ideally it would seamlessly compile FFI with [Babel](https://github.com/babel/babel-brunch) or [TypeScript](https://github.com//baptistedonaux/brunch-typescript) too. Inspired by [elm-brunch](https://github.com/madsflensted/elm-brunch) and [elm-brunch-starter](https://github.com/ivanoats/elm-brunch-starter).

**Comment by texastoland** [comment]
@paf31 This one is core in Elm but follows PS Bin on my personal todo regardless. Feel free to close.

**Comment by maddie927** [comment]
This would be big for me if it worked well with other CommonJS things like Babel.  Anything that makes it easier to add one or two lone PS files to an existing project will be a huge evangelism win too.  It's a weak point for Elm.

**Comment by texastoland** [comment]
^ That's why I think it should be official :) As old as Brunch is I'm not aware of another generic build-by-convention tool. They are either too general (Grunt, Gulp, NPM scripts) or too specific (every static site generator). It immediately follows PS Bin on my personal todo list in term of priorities (a couple parsing changes are in front).

**Comment by maddie927** [comment]
Yeah, you could also do webpack or browserify transforms, but they have more complicated/limited apis while also being less general than brunch.  Brunch seems like the right layer to fit into.

**Comment by paulyoung** [comment]
Putting this here for reference: https://github.com/rtfeldman/elm-webpack-loader

It was already in the back of my mind when I read this, and now webpack has been mentioned 😀

**Comment by garyb** [comment]
:zap: https://github.com/ethul/purs-loader

**Comment by paulyoung** [comment]
:raised_hands:

**Comment by maddie927** [comment]
Yeah, I've had mixed results with it.  It fits better into the JS ecosystem than PS.  For example you can't use the dead code elimination anymore (unless that's changed recently).  Brunch might have the same problems though.

**Comment by texastoland** [comment]
💥 I've been collecting thoughts what it would take to make PureScript a viable tool for consulting services (compiler stability aside). They revolve primarily around community building (hence the upcoming remote meetups), first-in-class tooling (hence this ticket), and accessible (both locatable and approachable) educational resources (upcoming Egghead videos just waiting for beginner friendly tools I'm hacking on). Would y'all be interested in me surfacing them somehow?

**Comment by texastoland** [comment]
This _is_ my immediate priority following PS Bin and `Witherable` but perhaps not a core utility. Closing here but keeping on my personal list.
