### ISSUE TITLE
Either FFI extensions

### ISSUE THREAD

**Issue by texastoland** [purescript/roadmap#47]
Conveniences for handling JavaScript exceptions and Node thunks. Inspired by [Result](https://github.com/antitypical/Result) from the Swift community. Originally suggested by @archaeron in paf31/purescript-preface#1.

**Comment by zudov** [comment]
I'll just drop a reference to Elm's `Result` as an additional source of inspiration http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Result

**Comment by zudov** [comment]
Although, it has nothing to do with exceptions and thunks, only the friendlier naming.

**Comment by paulyoung** [comment]
Here's my F# version, for reference: https://github.com/functionauts/Result

**Comment by texastoland** [comment]
@zudov Yeah Elm uses `Result` as an alias for `Either`. Likewise `formatError` looks like [`lmap`](https://pursuit.purescript.org/packages/purescript-bifunctors/0.4.0/docs/Data.Bifunctor#v:lmap). `to`/`fromMaybe` would be nice though! Ultimately we want an alternate prelude with beginner friendly naming too. But referencing a couple Swift implementations I noticed they took it a step further to encapsulate error handling.

@paulyoung Thanks! Very succinct and reassuring this is low hanging fruit. What's the use case for `dematerialize`?

**Comment by paulyoung** [comment]
@AppShipIt it's equivalent to [`dematerialize` in antitypical/Result](https://github.com/antitypical/Result/blob/8a61db0937f1942d045b87f813ba58b0c41c4cef/Result/Result.swift#L42) but I only really added it for interop with C# where an exception is expected to be thrown.

**Comment by texastoland** [comment]
Totally missed that thanks! May as well add for parity.

**Comment by paf31** [comment]
This seems like something which belongs in a user library, but not necessarily the core libraries. Automatic handling of exceptions is not the sort of "opinionated" (if you like) approach taken by core libraries.

**Comment by texastoland** [comment]
Ah didn't realize it was necessarily for core stuff (likewise #45). I opened the issue as a personal todo unless someone else wants to. Clarify <q>opinionated?</q> My idea was vaguely motivated by Harry's [`Eff` functions](https://pursuit.purescript.org/packages/purescript-eff-functions/0.1.1/docs/Data.Function.Eff). I just want to be able to consume an exception-al JS thing and not crash PS.

**Comment by texastoland** [comment]
Better implemented as an extension to `Either` with the `Result` nomenclature in Preface eventually. Closing as more of a community effort than necessarily official for the time being.
