### ISSUE TITLE
Curated list of blog posts

### ISSUE THREAD

**Issue by texastoland** [purescript/roadmap#48]
PureScript is evolving at a rate at which bit rot in old blog posts can confound newcomers. Not only would it be nice to aggregate articles but perhaps request authors to gist their examples so we can automate testing.

**Comment by paf31** [comment]
This could take the form of an aggregator. Or we could even encourage people to move their blog posts onto the main website.

**Comment by texastoland** [comment]
Both suggestions sound promising. Adobe used to have the former for Flex. The latter could be implemented as a multi-authorship community blog? Ghost is really good at that and could be enhanced for automated testing.
