### ISSUE TITLE
Style guide (code / syntax)

### ISSUE THREAD

**Issue by paulyoung** [purescript/roadmap#49]
Not to be confused with the [guidelines for writing libraries](https://github.com/purescript/purescript/wiki/Style-Guide), but something more in the style of [Elm's style guide](http://elm-lang.org/docs/style-guide) or [NoRedInk's Elm Style Guide](https://github.com/NoRedInk/elm-rails/wiki/NoRedInk's-Elm-Style-Guide).

**Comment by texastoland** [comment]
@paulyoung This is on my personal todo! I have concrete ideas if you'd like to coordinate? I was thinking of publishing it with GitBook for a whirlwind syntax tour.

**Comment by paulyoung** [comment]
Sounds great!

I may be providing more questions than answers 😄

**Comment by texastoland** [comment]
Sweet I'll gather my thoughts into a repo today!!

**Comment by texastoland** [comment]
@paulyoung I'm starting [here](https://github.com/AppShipIt/purescript-book) if you wanna follow along. I'll publish conventions first based on several Haskell and Elm guides. NB for pedagogical sake it won't follow the style of our Prelude or compiler.

**Comment by paulyoung** [comment]
@AppShipIt sounds good. Feel free to ping me if you make updates.

**Comment by tfausak** [comment]
I think this should go hand-in-hand with #23.

**Comment by texastoland** [comment]
I think #23 should be more flexible. At work I've pointed out the current conventions I deem awful e.g. vertical indentation. We're using recommendations based on Elm which I'll add to purescript-4humans.

**Comment by garyb** [comment]
What's "vertical indentation"?

**Comment by natefaubion** [comment]
> purescript-4humans

Next: purescript-4dolphins :wink:

**Comment by tfausak** [comment]
``` purescript
data Maybe a = Nothing
             | Just a
          -- ^ Lining this up is "vertical indentation".
```

Edit: ... I think.

**Comment by garyb** [comment]
The Elm style guide is against that too I thought? Unless I'm misunderstanding @AppShipIt.

:+1: for _not_ doing that.

**Comment by texastoland** [comment]
Right. Definitely planning on getting feedback!

**Comment by dkoontz** [comment]
👍  for this. I've also been using the Elm style guide for PS at work and it's been very nice.

**Comment by ianbollinger** [comment]
I started work on one [here](https://github.com/ianbollinger/purescript-style-guide/blob/master/purescript-style.md), if anyone is interested.

**Comment by paf31** [comment]
Moving to the docs repo.
